// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArf-bZckoonv8a_llZqNfE8a4gzlvLe4I',
    appId: '1:1098621906853:web:7325f0f05336f0d6ea424c',
    messagingSenderId: '1098621906853',
    projectId: 'community-connect-bkgsga',
    authDomain: 'community-connect-bkgsga.firebaseapp.com',
    storageBucket: 'community-connect-bkgsga.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYWS8O-FReax1ZdxqbrXaUNVBGM49Emk',
    appId: '1:1098621906853:android:d4481d6d0ae62f4eea424c',
    messagingSenderId: '1098621906853',
    projectId: 'community-connect-bkgsga',
    storageBucket: 'community-connect-bkgsga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2t-5SdAU7_wsIQYTjsY0-rRnw8sT_MCY',
    appId: '1:1098621906853:ios:906f09b427b762b4ea424c',
    messagingSenderId: '1098621906853',
    projectId: 'community-connect-bkgsga',
    storageBucket: 'community-connect-bkgsga.firebasestorage.app',
    iosBundleId: 'com.example.communityconnec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2t-5SdAU7_wsIQYTjsY0-rRnw8sT_MCY',
    appId: '1:1098621906853:ios:467720d74ef01b06ea424c',
    messagingSenderId: '1098621906853',
    projectId: 'community-connect-bkgsga',
    storageBucket: 'community-connect-bkgsga.firebasestorage.app',
    iosBundleId: 'com.example.community-connect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArf-bZckoonv8a_llZqNfE8a4gzlvLe4I',
    appId: '1:1098621906853:web:0570cd4191cc6d4eea424c',
    messagingSenderId: '1098621906853',
    projectId: 'community-connect-bkgsga',
    authDomain: 'community-connect-bkgsga.firebaseapp.com',
    storageBucket: 'community-connect-bkgsga.firebasestorage.app',
  );

}