# Generated by Django 5.2.5 on 2025-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
    ]
